### PR TITLE
Added data analysis plan, fixes #36

### LINKED ISSUE #36: Plan -> Stuart needs filling out before tomorrow

### PR DESCRIPTION
**Pull request by sashforth**

### CODE REVIEW

**Comment by Baltoli** [comment]
Seems good to me

**Comment by w-shackleton** [comment]
I think we are planning on having the data be sent every time unit

**Comment by Baltoli** [comment]
Yeah I think so - after the session ends could be indefinite

**Comment by sashforth** [comment]
Okay, will fix

**Comment by w-shackleton** [comment]
For future reference you can push more commits to the same branch and they automatically become part of the Pull request.

**Comment by w-shackleton** [comment]
I think each frame would be too much - we are hoping to get about 10FPS. Perhaps every minute or so?

**Comment by w-shackleton** [comment]
LGTM

**Pull request merged**
